fileno:fileno.c
	gcc -g $^ -o $@
buffer:buffer.c
	gcc -g $^ -o $@
review:review.c
	gcc -g $^ -o $@
sysio:sysio.c
	gcc -g $^ -o $@
minishell:minishell.c
	gcc $^ -o $@
.PHONY:clean
clean:
	rm minishell sysio review buffer fileno
